development:
  adapter: postgresql
  encoding: unicode
  database: cubert_development
  pool: 5
  username: nick
  password: nick
  host: localhost
  port: 5432

test:
  adapter: postgresql
  encoding: unicode
  database: cubert_test
  pool: 5
  username: nick
  password: nick
  host: localhost
  port: 5432
